/*
 * Takí Project
 *
 * IF683 Takí project
 *
 * API version: 1.0.0
 * Contact: mvgmb@cin.ufpe.br
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type Category struct {

	// Unique identifier representing a specific Category
	Id int32 `json:"_id,omitempty"`

	// Name of category
	Name string `json:"name,omitempty"`

	Image string `json:"image,omitempty"`

	// Description of category
	Description string `json:"description,omitempty"`
}
