/*
 * Takí Project
 *
 * IF683 Takí project
 *
 * API version: 1.0.0
 * Contact: mvgmb@cin.ufpe.br
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type Product struct {

	// Unique identifier representing a specific Product
	Id int32 `json:"_id,omitempty"`

	// Name of product
	Name string `json:"name,omitempty"`

	Image string `json:"image,omitempty"`

	// Description of product
	Description string `json:"description,omitempty"`
}
