version: '3'
services:
  database:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    ports:
      - 6603:3306
    restart: always
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    expose:
      - "8080"
    environment:
      - DB_ADDR=172.17.0.1
      - DB_PORT=6603
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=taki
    restart: always
    