/*
 * Takí Project
 *
 * IF683 Takí project
 *
 * API version: 1.0.0
 * Contact: mvgmb@cin.ufpe.br
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package server

type User struct {

	// Unique identifier representing a specific user
	Id int32 `json:"_id,omitempty"`

	// Name of user
	Name string `json:"name,omitempty"`

	// Age of user
	Age int32 `json:"age,omitempty"`

	// Sex of user
	Sex int32 `json:"sex,omitempty"`

	// E-mail of user
	Email string `json:"email,omitempty"`

	// Permission of user
	Permission string `json:"permission,omitempty"`
}
